name = "HydraulicFracturing"
uuid = "360e7545-1e44-46d1-a6c9-053fa4254e4a"
authors = ["bdas123 <barun.das@utexas.edu> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
